# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grow_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from download.download_product import DownloadProduct
from download.search_product import SearchProduct
from multiprocessing import Pool


class Ui_MainWindow(object):

    def __init__(self):
        self.start_date = None
        self.end_date = None
        self.spatial_tuple = tuple()
        self.satellite = None
        self.product = None
        self.download_url = list()
        self.thread_num = 6

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1251, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(187, 60, 104, 41))
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(230, 230, 31, 20))
        self.label_5.setObjectName("label_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_6.setGeometry(QtCore.QRect(187, 180, 104, 41))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(260, 640, 161, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(230, 30, 31, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(90, 90, 41, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(350, 170, 41, 20))
        self.label_4.setObjectName("label_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_5.setGeometry(QtCore.QRect(287, 120, 104, 41))
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(240, 570, 211, 51))
        self.label_11.setObjectName("label_11")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 480, 171, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(410, 330, 81, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(410, 400, 81, 21))
        self.label_14.setObjectName("label_14")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_7.setGeometry(QtCore.QRect(77, 120, 104, 41))
        self.textEdit_7.setObjectName("textEdit_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_2.setGeometry(QtCore.QRect(640, 50, 451, 601))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 260, 101, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(30)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(120, 250, 161, 281))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget1)
        self.dateEdit.setDate(QtCore.QDate(2023, 1, 1))
        self.dateEdit.setObjectName("dateEdit")

        # 设置可以弹出日历
        self.dateEdit.setCalendarPopup(True)

        self.gridLayout_2.addWidget(self.dateEdit, 0, 0, 1, 1)
        self.dateEdit_4 = QtWidgets.QDateEdit(self.layoutWidget1)
        self.dateEdit_4.setDate(QtCore.QDate(2023, 1, 1))
        self.dateEdit_4.setObjectName("dateEdit_4")

        # 设置可以弹出日历
        self.dateEdit_4.setCalendarPopup(True)

        self.gridLayout_2.addWidget(self.dateEdit_4, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(7)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 2, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setMaxVisibleItems(7)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 3, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setMaxVisibleItems(7)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 4, 0, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_3.setGeometry(QtCore.QRect(410, 360, 161, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_4.setGeometry(QtCore.QRect(410, 430, 161, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 560, 161, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 263, 171, 41))
        self.pushButton_2.setMinimumSize(QtCore.QSize(159, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(180, 80, 781, 581))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_6.clicked.connect(self.search_product)
        self.pushButton_2.clicked.connect(self.download_files)

    def get_search_params(self):
        self.start_date = self.dateEdit.date().toString('yyyy-MM-dd')
        self.end_date = self.dateEdit_4.date().toString('yyyy-MM-dd')
        self.spatial_tuple = (
            int(self.textEdit_7.toPlainText()),
            int(self.textEdit.toPlainText()),
            int(self.textEdit_5.toPlainText()),
            int(self.textEdit_6.toPlainText())
        )
        self.satellite = self.comboBox.currentText()
        self.product = self.comboBox_2.currentText()

        print(self.start_date)
        print(self.end_date)
        print(self.spatial_tuple)
        print(self.satellite)
        print(self.product)

    def search_product(self):
        self.get_search_params()
        sp = SearchProduct(self.start_date, self.end_date, self.spatial_tuple, self.product)
        self.download_url = sp.search_product()

    def download_files(self):
        dp = DownloadProduct()
        dp.get_token()
        dp.set_headers()
        self.textBrowser_3.setText(str(len(self.download_url)))
        if len(self.download_url) < self.thread_num:
            pool = Pool(len(self.download_url))
        else:
            pool = Pool(self.thread_num)
        pool.map(dp.download_file, self.download_url)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "下"))
        self.label.setText(_translate("MainWindow", "目标区域（十进制度）:"))
        self.pushButton_5.setText(_translate("MainWindow", "4.生成 NDVI 数据"))
        self.label_2.setText(_translate("MainWindow", "上"))
        self.label_3.setText(_translate("MainWindow", "左"))
        self.label_4.setText(_translate("MainWindow", "右"))
        self.label_11.setText(_translate("MainWindow", "请先验证所需文件都已下载完成！"))
        self.pushButton_4.setText(_translate("MainWindow", "3.验证下载"))
        self.label_13.setText(_translate("MainWindow", "总个数："))
        self.label_14.setText(_translate("MainWindow", "已下载："))
        self.label_6.setText(_translate("MainWindow", "起始日期："))
        self.label_9.setText(_translate("MainWindow", "终止日期："))
        self.label_7.setText(_translate("MainWindow", "目标卫星："))
        self.label_8.setText(_translate("MainWindow", "所需数据："))
        self.label_10.setText(_translate("MainWindow", "数据版本："))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.dateEdit_4.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.comboBox.setCurrentText(_translate("MainWindow", "MODIS:TERRA"))
        self.comboBox.setItemText(0, _translate("MainWindow", "MODIS:TERRA"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "MOD03"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "MOD03"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "MOD09GQ"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "MOD35_L2"))
        self.comboBox_3.setCurrentText(_translate("MainWindow", "1.0.1"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "1.0.1"))
        self.pushButton_6.setText(_translate("MainWindow", "1.检索数据"))
        self.pushButton_2.setText(_translate("MainWindow", "2.下载数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "数据处理"))
        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">二十一世纪空间技术应用有限公司</span></p>\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:700;\"><br /></p>\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:700;\"><br /></p>\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:700;\"><br /></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">产品名称：长势监测软件</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  产品类型：exe可执行程序</span></p>\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "软件信息"))
